settings:
  wait-chat-event-priority: HIGHEST
  chunk-view-material: RED_WOOL

lang:
  no-permission: "&cYou don't have permission to do that!"
  not-player: "&cYou must be a player to do that!"
  cancel-chat-wait: "Cancel"
  type-the-name-of-the-town: "&aType the name of the town you want to join or type &ccancel to cancel."
  chat-wait-cancelled: "&cCancelled your request!"
  title-too-long: "&cThe title is too long!"
  enter-title: "&aType in the title you would like to give to %player% now. Type &ccancel to cancel."
  you-cannot-select-yourself: "&cYou cannot select yourself!"
  enter-rank: "&aType in the rank you would like to give to %player% now. &b(Options: councillor, assistant, helper, sheriff, guard)&a. Type &ccancel to cancel or remove to remove the rank."
  rank-too-long: "&cThe rank is too long!"
  added-rank: "&aAdded rank &b%rank% &ato &b%player%&a!"
  added-title: "&aAdded title &b%title% &ato &b%player%&a!"
  kicked-player: "&aYou have been kicked from the town!"
  gave-mayor: "&aYou are now the mayor of the town!"
  invalid-rank: "&cInvalid rank!"
  removed-ranking: "&aRemoved rank &b%rank% &afrom &b%player%&a!"
  invalid-number: "&cInvalid number, please make sure the number is above 0!"
  enter-deposit: "&aType in the amount you would like to deposit to the town bank now. Type &ccancel to cancel."
  enter-withdraw: "&aType in the amount you would like to withdraw from the town bank now. Type &ccancel to cancel."
  enter-tax: "&aType in the amount you would like to set the tax percentage now. Type &ccancel to cancel."
  enter-deposit-nation: "&aType in the amount you would like to deposit to the nation bank now. Type &ccancel to cancel."
  enter-withdraw-nation: "&aType in the amount you would like to withdraw from the nation bank now. Type &ccancel to cancel."
  enter-tax-nation: "&aType in the amount you would like to set the tax percentage now. Type &ccancel to cancel."
  enter-name: "&aType in the name you would like to give to the town now. Type &ccancel to cancel."
  enter-board: "&aType in the board you would like to give to the town now. Type &ccancel to cancel."
  enter-name-nation: "&aType in the name you would like to give to the nation now. Type &ccancel to cancel."
  enter-board-nation: "&aType in the board you would like to give to the nation now. Type &ccancel to cancel."
  enter-sale-price: "&aType in the sale price you would like to give to the town now. Type &ccancel to cancel."
  enter-no-sale-price: "&aWould you like to set this price not for sale? Type confirm or &ccancel."
  enter-plot-type: "&aWhat type would you like to set this plot? &b(Options: arena, bank, defailt, embassy, farm, inn, jail, shop, wilds)&a. Type &ccancel to cancel."
  enter-evict-resident: "&aType in the name of the resident you would like to evict from the plot now. Type &ccancel to cancel."
  friend-added: "&aAdded &b%player% &ato your friends list!"
  friend-removed: "&aRemoved &b%player% &afrom your friends list!"
  not-in-claim: "&cYou are not in a claim!"
  type-the-name-of-the-nation: "&aType the name of the nation you want to join or type &ccancel to cancel."
  gave-king: "&aYou gave the king rank to &b%player%&a!"
  chunk-view-disabled: "&cChunk view is disabled!"
  chunk-view-enabled: "&aChunk view is enabled!"